import pandas as pd 
import matplotlib.pyplot as plt 
data = pd.read_csv("employees.csv")
print("Employee data")
print(data)
print("Employee info")
print(data.info())
average_salary = data["salary"].mean()
print("\nAverage salary",average_salary)
maximum_salary = data["salary"].max()
print("\n maximum salary:",maximum_salary)
dept_salary = data.groupby("department")["salary"].mean()
print("department wise salary :",dept_salary)
plt.figure(figsize=(6,4))
plt.bar(dept_salary.index,dept_salary.values)
plt.title("department wise average salary")
plt.xlabel("department of system")
plt.ylabel("average salary of employee")
plt.show()
gender_count = data["gender"].value_counts()
plt.figure(figsize=(5,5))
plt.pie(gender_count,labels = gender_count.index)
plt.title("gender domination")
plt.show()
plt.scatter(data["exp"],data["salary"])
plt.title("experiance vs salary")
plt.xlabel("exp")
plt.ylabel("salary")
plt.show()


